name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Ensure instance directory
        run: |
          New-Item -ItemType Directory -Force -Path instance | Out-Null

      - name: Initialize database (seed admin/processes)
        run: |
          python init_db.py

      - name: Copy DB into instance for backup/restore features
        run: |
          if (Test-Path .\oleema.db) {
            New-Item -ItemType Directory -Force -Path instance | Out-Null
            Copy-Item .\oleema.db .\instance\oleema.db -Force
          }

      - name: Build with PyInstaller
        # On Windows, PyInstaller --add-data uses a semicolon to separate src;dest
        run: |
          pyinstaller --noconfirm --clean \
            --name Oleema \
            --add-data "oleema.db;." \
            --add-data "templates;templates" \
            --add-data "static;static" \
            --add-data "instance;instance" \
            app.py

      - name: Archive artifact
        run: |
          Compress-Archive -Path dist\Oleema\* -DestinationPath Oleema-Windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Oleema-Windows
          path: Oleema-Windows.zip


